### ISSUE TITLE
pony skin probloms

### ISSUE THREAD

**Issue by TheAnonPonyPoster** [MineLittlePony/MineLittlePony#12] opened 2016-07-14 10:30 UTC
the skins arnt updateing when i change them on the 1.10.2 and 1.9.4 versons i havent tryed anything below but please tell me hwo to fix them...

**Comment by killjoy1221** [comment] 2016-07-14 18:28
Duplicate of #5
Wait a few hours

**Closed by killjoy1221** 2016-07-14 18:28 UTC
