### ISSUE TITLE
Silence trim disappears depending on camera

### ISSUE THREAD

**Issue by derram** [MineLittlePony/MineLittlePony#270] opened 2024-03-17 15:42 UTC
The trim will disappear from the helmet and boots depending on the camera angle, seems to only happen when boots and helmet are equipped at the same time. 

![2024-03-17_10 37 38](https://github.com/MineLittlePony/MineLittlePony/assets/5730335/8cf06db8-91f1-4ea3-b650-be5028d79747)

![2024-03-17_10 37 47](https://github.com/MineLittlePony/MineLittlePony/assets/5730335/a291ea92-26ad-4ed4-95aa-1ad5b37ff533)

**Comment by Sollace** [comment] 2024-04-16 16:21
Probably a duplicate of #269

**Closed as completed** 2024-05-05 17:32 UTC
Labels: bug
