### ISSUE TITLE
'Unsupported image format' crash on macOS

### ISSUE THREAD

**Issue by endorfina** [MineLittlePony/MineLittlePony#136] opened 2019-10-14 08:49 UTC
The following exception is thrown on macOS right after the `Endorfina joined the game` message in the logs.

I've checked different java versions and an identical setup on Windows 10 and GNU/Linux. The crash occurs only on macOS.

```
Error executing task on Client
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Unsupported image format
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.minelittlepony.client.pony.PonyManager.getPony(PonyManager.java:71)
	at com.minelittlepony.client.pony.PonyManager.getBackgroundPony(PonyManager.java:141)
	at com.minelittlepony.client.pony.PonyManager.getDefaultPony(PonyManager.java:130)
	at com.minelittlepony.client.pony.PonyManager.getPony(PonyManager.java:80)
	at net.minecraft.class_746.method_18394(class_746.java:1207)
	at net.minecraft.class_1309.method_18378(class_1309.java:2855)
	at net.minecraft.class_1297.<init>(class_1297.java:250)
	at net.minecraft.class_1309.<init>(class_1309.java:202)
	at net.minecraft.class_1657.<init>(class_1657.java:199)
	at net.minecraft.class_742.<init>(class_742.java:48)
	at net.minecraft.class_746.<init>(class_746.java:136)
	at net.minecraft.class_636.method_2901(class_636.java:357)
	at net.minecraft.class_634.method_11120(class_634.java:354)
	at net.minecraft.class_2678.method_11567(class_2678.java:76)
	at net.minecraft.class_2678.method_11054(class_2678.java:13)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.class_1255.method_5383(class_1255.java:103)
	at net.minecraft.class_310.method_1523(class_310.java:915)
	at net.minecraft.class_310.method_1514(class_310.java:410)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:178)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.RuntimeException: Unsupported image format
	at com.minelittlepony.client.util.render.NativeUtil.getFormat(NativeUtil.java:26)
	at com.minelittlepony.client.util.render.NativeUtil.parseImage(NativeUtil.java:48)
	at com.minelittlepony.client.pony.PonyData.parse(PonyData.java:59)
	at com.minelittlepony.client.pony.Pony.<init>(Pony.java:45)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:146)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 33 more

Error executing task on Client
java.lang.NullPointerException
	at net.minecraft.class_634.method_11152(class_634.java:1753)
	at net.minecraft.class_2658.method_11457(class_2658.java:62)
	at net.minecraft.class_2658.method_11054(class_2658.java:10)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.class_1255.method_5383(class_1255.java:103)
	at net.minecraft.class_310.method_1523(class_310.java:915)
	at net.minecraft.class_310.method_1514(class_310.java:410)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:178)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
```

**Comment by Sollace** [comment] 2019-10-14 10:40
Duplicate of #133

**Closed by Sollace** 2019-10-14 10:40 UTC
Labels: duplicate
