### ISSUE TITLE
Crash while rendering self 1.15-4.0

### ISSUE THREAD

**Issue by derram** [MineLittlePony/MineLittlePony#146] opened 2020-01-29 08:37 UTC
[crash-2020-01-29_01.55.39-client.txt](https://github.com/MineLittlePony/MineLittlePony/files/4126894/crash-2020-01-29_01.55.39-client.txt)

A player on my server was experiencing a crash, log seems to indicate it has something to do with rendering his own model.

Crash happened after he had been playing for a while, after multiple sessions with the mod installed. Happened repeatedly, but he's not sure how to reproduce it since he was able to get back on later and continue playing.

Player is using a pegasus model.

**Comment by Sollace** [comment] 2020-01-29 08:41
Duplicate of https://github.com/MineLittlePony/Mson/issues/2

**Closed by Sollace** 2020-01-29 08:41 UTC
