### ISSUE TITLE
Maybe disable Elytra for Pegasi?

### ISSUE THREAD

**Issue by Aquaeyes** [MineLittlePony/MineLittlePony#42] opened 2018-01-15 14:53 UTC
I'm saying this because editing the elytra through the menu doesn't seem to be a thing that works. So a toggleable thing in the F9 menu might be a good idea for a way to disable elytra for Pegasi, or maybe a custom pixel to disable it?

**Comment by Sollace** [comment] 2019-07-11 17:25
Closing this as it's a "wontfix", works as intended.

**Closed by Sollace** 2019-07-11 17:25 UTC
Labels: models, wontfix
