### ISSUE TITLE
1.14.4 Minecraft "Saves World" and quits when attempting to render a pony

### ISSUE THREAD

**Issue by stellopsia** [MineLittlePony/MineLittlePony#133] opened 2019-09-16 06:08 UTC
This crash occurs in an isolated game folder (as close as I can get without reinstalling the whole game, launcher and all) with only combinations of the fabric API, MineLP and HDSkin installed.

When MineLP is in the mods folder and I attempt to load a world, it shows the normal progress indicators right up to 100%, then displays a "Saving world" screen before exiting to desktop.

HDSkins doesn't exhibit the problem itself, but I can cause the same behavior (minus world loading, but curiously with world saving) by trying to open the HDSkin skin viewer when MineLP is installed.

My first instinct was that there might be a problem with my skin, but using the online tools I determined that the mods would not find any skin corresponding to my account. So it seems like the problem is related to rendering a pony model, either in-game or in menus.

I consequently have two sets of log/crash files to include, mildly edited to exclude username information; the earlier set corresponds to attempted world loading, the latter with the HDSkin interface. Hopefully a comparison of the two cases will help isolate the cause.

[2019-09-15-1.log](https://github.com/MineLittlePony/MineLittlePony/files/3614872/2019-09-15-1.log)
[crash-2019-09-15_23.22.00-client.txt](https://github.com/MineLittlePony/MineLittlePony/files/3614871/crash-2019-09-15_23.22.00-client.txt)

[2019-09-16-1.log](https://github.com/MineLittlePony/MineLittlePony/files/3614873/2019-09-16-1.log)
[crash-2019-09-16_00.19.31-client.txt](https://github.com/MineLittlePony/MineLittlePony/files/3614870/crash-2019-09-16_00.19.31-client.txt)

**Comment by Sollace** [comment] 2019-09-16 06:39
What operating system are you running?

**Comment by killjoy1221** [comment] 2019-09-16 13:26
> Mac OS X (x86_64) version 10.14.6

**Comment by Twinkle-Sprinkle** [comment] 2019-09-16 13:32
windows7 ultimate with sp1 x64
minecraft launcher:Hello Minecraft! Launcher 3.2 HMCL 启动器
(https://github.com/huanghongxun/HMCL/)

------------------ Original ------------------

**Comment by Sollace** [comment] 2019-09-16 16:25
@killjoy1221 Right. That's what I suspected.

@stellopsia Until I can properly investigate this, I'm going to have to suggest as a fix not to use a Mac.

**Comment by killjoy1221** [comment] 2019-09-16 16:33
It being a mac is likely *NOT* the cause.

**Comment by Sollace** [comment] 2019-09-16 16:52
@killjoy1221 Maybe not, but thus far of the two people who reported this, both have been using a Mac. The error is because for some reason the image format GL11 is returning isn't one of the ones mojang has specified support for.

I can stop it from crashing, but first I'd like to find out what this mystery "junk" value is, and why it only seems to appear on Mac/OSX.

@stellopsia Please try with this build (unzip it) and tell me what the error is that you get.
[MineLittlePony-1.14.4-3.3.1-SNAPSHOT.zip](https://github.com/MineLittlePony/MineLittlePony/files/3617282/MineLittlePony-1.14.4-3.3.1-SNAPSHOT.zip)

**Comment by stellopsia** [comment] 2019-09-17 01:20
Unsupported image format: 32856

**Comment by nrawling** [comment] 2019-09-30 23:48
I'm also having this problem.

**Comment by Sollace** [comment] 2019-10-04 16:37
Will be fixed in the next update https://github.com/MineLittlePony/MineLittlePony/commit/5e4d27181e55b07967759b425bda4a6eae7ad4e7

**Closed by Sollace** 2019-10-04 16:37 UTC
Labels: bug, incompatibility
