### ISSUE TITLE
[1.14.3 pre Linux] Game crashes when setting local legacy skin

### ISSUE THREAD

**Issue by derram** [MineLittlePony/MineLittlePony#117] opened 2019-07-02 07:10 UTC
[crash-2019-07-02_01.57.08-client.txt](https://github.com/MineLittlePony/MineLittlePony/files/3348713/crash-2019-07-02_01.57.08-client.txt)

Tried with several skins, including one from the Mine Little Pony skin pack. Haven't tested with any non-legacy skins because I'm not sure where to find any.

I happen to have a legacy skin currently set on the default minecraft skin server from doing some testing with the 1.8 version of the mod and it loads into the a world fine, but using the skin selector crashes the game.

**Comment by Sollace** [comment] 2019-07-02 07:21
The skin pack shouldn't contain any legacy skins at this point. They've all been converted to the 64x64 format.

**Comment by Sollace** [comment] 2019-07-02 07:23
Looks like an issue with the legacy skin conversion.

**Comment by derram** [comment] 2019-07-02 07:42
The crash log was from an attempt to use the default Pinkie Pie skin from the skin pack.

Maybe it has something to do with the fact that I'm using legacy skin on the minecraft skin server?

**Comment by Sollace** [comment] 2019-07-02 07:54
Nah. I know what the issue is. For now you can use the skins from the pack over here: https://github.com/MineLittlePony/Community-Skin-Pack

I'll try to get conversion fixed in the next pre-release.

**Comment by derram** [comment] 2019-07-02 08:01
Skin from that pack worked, thanks!

Side note though, in the middle of this I got optifine working with fabric and the skin preview on the selector disappeared.

**Closed** 2019-07-02 09:53 UTC
Labels: bug

**Comment by Sollace** [comment] 2019-07-02 09:59
@derram Optifabric is a whole other can of worms. Make a new issue with your game's logs and I'll try to fix it when I can.
